### ISSUE TITLE
Implement UI according to the design proposal

### ISSUE THREAD

**Issue by illia-kriukov** [illia-kriukov/svs-google-docs-add-on#17]
// example of useful html loader
https://www.w3schools.com/howto/howto_css_loader.asp

**Comment by aperkaz** [comment]
Important, the url of the sign in process image (the drawing pen image) is down. [http://www.waremakers.com/sites/default/files/pens_fountain_pen_1.png].
![capture](https://cloud.githubusercontent.com/assets/16224847/24837655/4a9e9d8a-1d39-11e7-853c-970a587d7474.PNG)

**Comment by illia-kriukov** [comment]
I created an issue regarding the pen image. See #29.
