### ISSUE TITLE
Set up install process with Node.js

### ISSUE THREAD

**Issue by illia-kriukov** [illia-kriukov/svs-google-docs-add-on#2]

**Comment by aperkaz** [comment]
I recomend we use NPM script for building and deploying (executing the needed comands for linting the JS and uploading everithing to Google Scripts). However every developer will follow their gapps config process and own a different Google Script project.

**Comment by aperkaz** [comment]
I have been checking the documentation of node-google-apps-script, which uses node to authenticate with google, push everything... And it also does sintax checking before pushing. I dont know if it makes a lot of sense to build node based scripts, when node-gapps offers what we need. For linting the JS i would propose adding a plugin to the prefered editor (Sublime, Atom...) that does the JS hinting.

**Comment by illia-kriukov** [comment]
If it will not take a lot of time to build node-google-apps-script I think it will be better to have that script. Otherwise, we can skip it in case if we can handle all necessary steps with node-gapps command only.

**Comment by aperkaz** [comment]
My bad, i already configured and tested node-google-apps-script. I think its enought for the development. In the last comment i meant, that we dont need to build a custom node.js dev pipeline, using node-google-apps-script its enought. If you have any doubt when following the tuto (https://www.npmjs.com/package/node-google-apps-script), just wrote me, but i think you wont have any trouble :) .

**Comment by illia-kriukov** [comment]
Ok, I will check it as soon as possible :)
