### ISSUE TITLE
Adjust UI according to our authentication

### ISSUE THREAD

**Issue by jikalousek** [illia-kriukov/svs-google-docs-add-on#20]
Integrate one more state that is shown at the start when a user is not signed in. It consists of form for inserting nickname (email address) and password. Successful login leads to "Sign this document" state, unsuccessful login leads to the same login page with error message.

**Comment by illia-kriukov** [comment]
Yuo can also show the message after the form regarding "Sign up". Something like "Do not have an account? Use our mobile application to sign up."
