### ISSUE TITLE
Set up Google Authentication

### ISSUE THREAD

**Issue by illia-kriukov** [illia-kriukov/svs-google-docs-add-on#3]
// extract oauthToken
https://developers.google.com/apps-script/reference/script/script-app#getOAuthToken()
// integrate google sign in in web app
https://developers.google.com/identity/sign-in/web/sign-in
// oauth 2 inside google apps
https://github.com/googlesamples/apps-script-oauth2

**Comment by jikalousek** [comment]
Maybe this task is not up to date anymore.

**Comment by illia-kriukov** [comment]
Yes. Closed it.
